### ISSUE TITLE
Transferred token is shown under "Currently holding"

### ISSUE THREAD

**Issue by borgersen** [elsewhat/nft-profit-loss#24]
Highlighted token has been transfered to another wallet, yet it is shown under "Currently holding"

![image](https://user-images.githubusercontent.com/6428276/141478962-f85570c1-384b-48fe-89cd-00deb80c63ac.png)

**Comment by elsewhat** [comment]
Like happens if both sellTransaction and buyTransaction are transfer events.

Will fix together with #12

**Comment by elsewhat** [comment]
Fixed
![image](https://user-images.githubusercontent.com/1133607/141677528-39b82ace-a4b5-429f-aa04-3437459e98b7.png)
